# how to use run command in makefile
# make run dir=/home/ahmed/Documents/dir backupdir=/home/ahmed/Documents/backupdir/ interval-secs=2 max-backups=4

dir=""
backupdir=""
interval-secs=""
max-backups=""

run:
	./script.sh $(dir) $(backupdir) $(interval-secs) $(max-backups)
